// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/kartmatias/cdwk-pos-agent/dao/model"
)

func newCore(db *gorm.DB, opts ...gen.DOOption) core {
	_core := core{}

	_core.coreDo.UseDB(db, opts...)
	_core.coreDo.UseModel(&model.Core{})

	tableName := _core.coreDo.TableName()
	_core.ALL = field.NewAsterisk(tableName)
	_core.Codigo = field.NewInt64(tableName, "Codigo")
	_core.Descricao = field.NewString(tableName, "Descricao")
	_core.Almox = field.NewBool(tableName, "Almox")
	_core.DPA = field.NewBool(tableName, "DPA")
	_core.Sigla = field.NewString(tableName, "Sigla")

	_core.fillFieldMap()

	return _core
}

type core struct {
	coreDo coreDo

	ALL       field.Asterisk
	Codigo    field.Int64
	Descricao field.String
	Almox     field.Bool
	DPA       field.Bool
	Sigla     field.String

	fieldMap map[string]field.Expr
}

func (c core) Table(newTableName string) *core {
	c.coreDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c core) As(alias string) *core {
	c.coreDo.DO = *(c.coreDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *core) updateTableName(table string) *core {
	c.ALL = field.NewAsterisk(table)
	c.Codigo = field.NewInt64(table, "Codigo")
	c.Descricao = field.NewString(table, "Descricao")
	c.Almox = field.NewBool(table, "Almox")
	c.DPA = field.NewBool(table, "DPA")
	c.Sigla = field.NewString(table, "Sigla")

	c.fillFieldMap()

	return c
}

func (c *core) WithContext(ctx context.Context) *coreDo { return c.coreDo.WithContext(ctx) }

func (c core) TableName() string { return c.coreDo.TableName() }

func (c core) Alias() string { return c.coreDo.Alias() }

func (c core) Columns(cols ...field.Expr) gen.Columns { return c.coreDo.Columns(cols...) }

func (c *core) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *core) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["Codigo"] = c.Codigo
	c.fieldMap["Descricao"] = c.Descricao
	c.fieldMap["Almox"] = c.Almox
	c.fieldMap["DPA"] = c.DPA
	c.fieldMap["Sigla"] = c.Sigla
}

func (c core) clone(db *gorm.DB) core {
	c.coreDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c core) replaceDB(db *gorm.DB) core {
	c.coreDo.ReplaceDB(db)
	return c
}

type coreDo struct{ gen.DO }

func (c coreDo) Debug() *coreDo {
	return c.withDO(c.DO.Debug())
}

func (c coreDo) WithContext(ctx context.Context) *coreDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c coreDo) ReadDB() *coreDo {
	return c.Clauses(dbresolver.Read)
}

func (c coreDo) WriteDB() *coreDo {
	return c.Clauses(dbresolver.Write)
}

func (c coreDo) Session(config *gorm.Session) *coreDo {
	return c.withDO(c.DO.Session(config))
}

func (c coreDo) Clauses(conds ...clause.Expression) *coreDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c coreDo) Returning(value interface{}, columns ...string) *coreDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c coreDo) Not(conds ...gen.Condition) *coreDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c coreDo) Or(conds ...gen.Condition) *coreDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c coreDo) Select(conds ...field.Expr) *coreDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c coreDo) Where(conds ...gen.Condition) *coreDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c coreDo) Order(conds ...field.Expr) *coreDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c coreDo) Distinct(cols ...field.Expr) *coreDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c coreDo) Omit(cols ...field.Expr) *coreDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c coreDo) Join(table schema.Tabler, on ...field.Expr) *coreDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c coreDo) LeftJoin(table schema.Tabler, on ...field.Expr) *coreDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c coreDo) RightJoin(table schema.Tabler, on ...field.Expr) *coreDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c coreDo) Group(cols ...field.Expr) *coreDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c coreDo) Having(conds ...gen.Condition) *coreDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c coreDo) Limit(limit int) *coreDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c coreDo) Offset(offset int) *coreDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c coreDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *coreDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c coreDo) Unscoped() *coreDo {
	return c.withDO(c.DO.Unscoped())
}

func (c coreDo) Create(values ...*model.Core) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c coreDo) CreateInBatches(values []*model.Core, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c coreDo) Save(values ...*model.Core) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c coreDo) First() (*model.Core, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Core), nil
	}
}

func (c coreDo) Take() (*model.Core, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Core), nil
	}
}

func (c coreDo) Last() (*model.Core, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Core), nil
	}
}

func (c coreDo) Find() ([]*model.Core, error) {
	result, err := c.DO.Find()
	return result.([]*model.Core), err
}

func (c coreDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Core, err error) {
	buf := make([]*model.Core, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c coreDo) FindInBatches(result *[]*model.Core, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c coreDo) Attrs(attrs ...field.AssignExpr) *coreDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c coreDo) Assign(attrs ...field.AssignExpr) *coreDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c coreDo) Joins(fields ...field.RelationField) *coreDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c coreDo) Preload(fields ...field.RelationField) *coreDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c coreDo) FirstOrInit() (*model.Core, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Core), nil
	}
}

func (c coreDo) FirstOrCreate() (*model.Core, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Core), nil
	}
}

func (c coreDo) FindByPage(offset int, limit int) (result []*model.Core, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c coreDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c coreDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c coreDo) Delete(models ...*model.Core) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *coreDo) withDO(do gen.Dao) *coreDo {
	c.DO = *do.(*gen.DO)
	return c
}
