// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/kartmatias/cdwk-pos-agent/dao/model"
)

func newLoja(db *gorm.DB, opts ...gen.DOOption) loja {
	_loja := loja{}

	_loja.lojaDo.UseDB(db, opts...)
	_loja.lojaDo.UseModel(&model.Loja{})

	tableName := _loja.lojaDo.TableName()
	_loja.ALL = field.NewAsterisk(tableName)
	_loja.Codigo = field.NewInt64(tableName, "Codigo")
	_loja.RazaoSocial = field.NewString(tableName, "RazaoSocial")
	_loja.Fantasia = field.NewString(tableName, "Fantasia")
	_loja.Endereco = field.NewString(tableName, "Endereco")
	_loja.CEP = field.NewString(tableName, "CEP")
	_loja.Bairro = field.NewString(tableName, "Bairro")
	_loja.UF = field.NewString(tableName, "UF")
	_loja.Cidade = field.NewString(tableName, "Cidade")
	_loja.Fone = field.NewString(tableName, "Fone")
	_loja.Fax = field.NewString(tableName, "Fax")
	_loja.CNPJ = field.NewString(tableName, "CNPJ")
	_loja.CGF = field.NewString(tableName, "CGF")
	_loja.Contato = field.NewString(tableName, "Contato")
	_loja.Celular = field.NewString(tableName, "Celular")
	_loja.DataCadastro = field.NewTime(tableName, "DataCadastro")
	_loja.Tabela = field.NewInt64(tableName, "Tabela")
	_loja.Email = field.NewString(tableName, "Email")
	_loja.Franquia = field.NewBool(tableName, "Franquia")
	_loja.Regime = field.NewBool(tableName, "Regime")
	_loja.TipodaLoja = field.NewInt64(tableName, "TipodaLoja")
	_loja.Senha = field.NewString(tableName, "Senha")
	_loja.SenhaSupervisor = field.NewString(tableName, "SenhaSupervisor")
	_loja.MetaDiariaValor = field.NewField(tableName, "MetaDiariaValor")
	_loja.MetaDiariaPecas = field.NewInt64(tableName, "MetaDiariaPecas")
	_loja.InativarClienteAposMesesSemComprar = field.NewInt64(tableName, "InativarClienteAposMesesSemComprar")
	_loja.Arredondamento = field.NewField(tableName, "Arredondamento")
	_loja.DescontoMaximo = field.NewField(tableName, "DescontoMaximo")
	_loja.DescontoMaximoFuncionario = field.NewField(tableName, "DescontoMaximoFuncionario")
	_loja.DescontosemCorretor = field.NewFloat64(tableName, "DescontosemCorretor")
	_loja.MinimoparaAtacadoValor = field.NewInt64(tableName, "MinimoparaAtacadoValor")
	_loja.QtdepcAtacado = field.NewInt64(tableName, "QtdepcAtacado")
	_loja.PercentuaMaximodeRetornodeConsignacao = field.NewInt64(tableName, "PercentuaMaximodeRetornodeConsignacao")
	_loja.MensagemparaComandadeVenda = field.NewString(tableName, "MensagemparaComandadeVenda")
	_loja.PadraoComanda = field.NewInt64(tableName, "PadraoComanda")
	_loja.CodigoNomeEmpresaACFiscal = field.NewString(tableName, "CodigoNomeEmpresaACFiscal")
	_loja.CodigoParticipanteACFiscal = field.NewInt64(tableName, "CodigoParticipanteACFiscal")
	_loja.EnviarICMSArquivoFortes = field.NewBool(tableName, "EnviarICMSArquivoFortes")
	_loja.Inativo = field.NewBool(tableName, "Inativo")
	_loja.ObsRegime1 = field.NewString(tableName, "ObsRegime1")
	_loja.ObsRegime2 = field.NewString(tableName, "ObsRegime2")
	_loja.ObsRegime3 = field.NewString(tableName, "ObsRegime3")
	_loja.ObsRegime4 = field.NewString(tableName, "ObsRegime4")
	_loja.CSTPIS = field.NewString(tableName, "CST_PIS")
	_loja.CSTCOFINS = field.NewString(tableName, "CST_COFINS")
	_loja.AliquotaPIS = field.NewFloat64(tableName, "Aliquota_PIS")
	_loja.AliquotaCOFINS = field.NewFloat64(tableName, "Aliquota_COFINS")
	_loja.SerieCertificadoDigital = field.NewString(tableName, "SerieCertificadoDigital")
	_loja.CaminhoLogotipoDanfe = field.NewString(tableName, "CaminhoLogotipoDanfe")
	_loja.CSTICMS = field.NewString(tableName, "CST_ICMS")
	_loja.CNPJCPFCertificadoDigital = field.NewString(tableName, "CNPJCPFCertificadoDigital")
	_loja.RegimeTributario = field.NewInt64(tableName, "RegimeTributario")
	_loja.CSOSN = field.NewInt64(tableName, "CSOSN")
	_loja.UtilizarAliquotaICMSCadastroCFOP = field.NewBool(tableName, "UtilizarAliquotaICMSCadastroCFOP")
	_loja.NFeAmbiente = field.NewString(tableName, "NFeAmbiente")
	_loja.NFeAtivaTrace = field.NewString(tableName, "NFeAtivaTrace")
	_loja.NFeCNPJ = field.NewString(tableName, "NFeCNPJ")
	_loja.NFeContigencia = field.NewString(tableName, "NFeContigencia")
	_loja.NFeDanfeInfo = field.NewString(tableName, "NFeDanfeInfo")
	_loja.NFeDanfeLogo = field.NewString(tableName, "NFeDanfeLogo")
	_loja.NFeDataPacket = field.NewString(tableName, "NFeDataPacket")
	_loja.NFeDataPacketFormSeg = field.NewString(tableName, "NFeDataPacketFormSeg")
	_loja.NFeModelo = field.NewString(tableName, "NFeModelo")
	_loja.NFeCancelamento = field.NewString(tableName, "NFeCancelamento")
	_loja.NFeConsultaCadastro = field.NewString(tableName, "NFeConsultaCadastro")
	_loja.NFeConsultaProtocolo = field.NewString(tableName, "NFeConsultaProtocolo")
	_loja.NFeInutilizacao = field.NewString(tableName, "NFeInutilizacao")
	_loja.NFeRecepcao = field.NewString(tableName, "NFeRecepcao")
	_loja.NFeRetRecepcao = field.NewString(tableName, "NFeRetRecepcao")
	_loja.NFeStatusServico = field.NewString(tableName, "NFeStatusServico")
	_loja.NFeNoSerieCertificado = field.NewString(tableName, "NFeNoSerieCertificado")
	_loja.NFePathPrincipal = field.NewString(tableName, "NFePathPrincipal")
	_loja.NFeSchemas = field.NewString(tableName, "NFeSchemas")
	_loja.NFeSerie = field.NewString(tableName, "NFeSerie")
	_loja.NFeTipoDanfe = field.NewString(tableName, "NFeTipoDanfe")
	_loja.NFeTotalizarCfop = field.NewString(tableName, "NFeTotalizarCfop")
	_loja.NFeUnidadeFederada = field.NewString(tableName, "NFeUnidadeFederada")
	_loja.NFeUnidadeFederadaCodigo = field.NewString(tableName, "NFeUnidadeFederadaCodigo")
	_loja.NFeVerProc = field.NewString(tableName, "NFeVerProc")
	_loja.NFeEmail = field.NewString(tableName, "NFeEmail")
	_loja.NFeNomeExibicaoEmail = field.NewString(tableName, "NFeNomeExibicaoEmail")
	_loja.NFeSenhaEmail = field.NewString(tableName, "NFeSenhaEmail")
	_loja.NFeServidorSMTPEmail = field.NewString(tableName, "NFeServidorSMTPEmail")
	_loja.NFeSSLEmail = field.NewString(tableName, "NFeSSLEmail")
	_loja.NFeHostProxy = field.NewString(tableName, "NFeHostProxy")
	_loja.NFePortaProxy = field.NewString(tableName, "NFePortaProxy")
	_loja.NFeSenhaProxy = field.NewString(tableName, "NFeSenhaProxy")
	_loja.NFeUsuarioProxy = field.NewString(tableName, "NFeUsuarioProxy")
	_loja.MensagemparacomandadeConsignacao = field.NewString(tableName, "MensagemparacomandadeConsignacao")
	_loja.Gerente = field.NewInt64(tableName, "Gerente")
	_loja.CodigoEstabelecimentoACFiscal = field.NewInt64(tableName, "CodigoEstabelecimentoACFiscal")
	_loja.NFeRecepcaoEvento = field.NewString(tableName, "NFeRecepcaoEvento")
	_loja.NFeDanfeCanhoto = field.NewString(tableName, "NFeDanfeCanhoto")
	_loja.NFeDanfeTpDesc = field.NewString(tableName, "NFeDanfeTpDesc")
	_loja.NFeFormatoItemQtd = field.NewString(tableName, "NFeFormatoItemQtd")
	_loja.NFeFormatoItemUnt = field.NewString(tableName, "NFeFormatoItemUnt")
	_loja.NFeSizeFontObs = field.NewString(tableName, "NFeSizeFontObs")
	_loja.NFeValASS = field.NewString(tableName, "NFeVal_ASS")
	_loja.NFeValMD5 = field.NewString(tableName, "NFeVal_MD5")
	_loja.PRPercentual = field.NewFloat64(tableName, "PRPercentual")
	_loja.PRQtdeDiasLimite = field.NewInt64(tableName, "PRQtdeDiasLimite")
	_loja.PRQtdeVendaPremiar = field.NewInt64(tableName, "PRQtdeVendaPremiar")
	_loja.UtilizaPremiacaoCorretor = field.NewBool(tableName, "UtilizaPremiacaoCorretor")
	_loja.InformarPISCOFINSArquivoFortes = field.NewBool(tableName, "InformarPISCOFINSArquivoFortes")
	_loja.AddMensVendaNoOrcamento = field.NewBool(tableName, "addMensVendaNoOrcamento")
	_loja.DescontoMaximoVarejo = field.NewInt64(tableName, "DescontoMaximoVarejo")
	_loja.ObrigaTelefoneCliente = field.NewBool(tableName, "ObrigaTelefoneCliente")
	_loja.NFeAutorizacao = field.NewString(tableName, "NFeAutorizacao")
	_loja.NFeRetAutorizacao = field.NewString(tableName, "NFeRetAutorizacao")
	_loja.ImprimeVendaBobina = field.NewBool(tableName, "ImprimeVendaBobina")
	_loja.LojaOnLine = field.NewBool(tableName, "LojaOnLine")
	_loja.NFCeAmbiente = field.NewInt64(tableName, "NFCeAmbiente")
	_loja.NFCeModelo = field.NewInt64(tableName, "NFCeModelo")
	_loja.NFCePathPrincipal = field.NewString(tableName, "NFCePathPrincipal")
	_loja.NFCeSerie = field.NewInt64(tableName, "NFCeSerie")
	_loja.NFCeTipoDanfe = field.NewInt64(tableName, "NFCeTipoDanfe")
	_loja.NFCeVersaoXML = field.NewString(tableName, "NFCeVersaoXML")
	_loja.CalculaTributosAproximados = field.NewBool(tableName, "CalculaTributosAproximados")
	_loja.DescontoSuframa = field.NewFloat64(tableName, "DescontoSuframa")
	_loja.DataFinalPeriodoBase = field.NewTime(tableName, "DataFinalPeriodoBase")
	_loja.SaldoICMS = field.NewField(tableName, "SaldoICMS")
	_loja.SaldoICMSTipo = field.NewString(tableName, "SaldoICMS_Tipo")
	_loja.SaldoIPI = field.NewField(tableName, "SaldoIPI")
	_loja.SaldoIPITipo = field.NewString(tableName, "SaldoIPI_Tipo")
	_loja.SaldoCOFINS = field.NewField(tableName, "SaldoCOFINS")
	_loja.SaldoCOFINSTipo = field.NewString(tableName, "SaldoCOFINS_Tipo")
	_loja.SaldoPIS = field.NewField(tableName, "SaldoPIS")
	_loja.SaldoPISTipo = field.NewString(tableName, "SaldoPIS_Tipo")
	_loja.Numero = field.NewString(tableName, "Numero")
	_loja.CodigoContabilista = field.NewInt64(tableName, "CodigoContabilista")
	_loja.InformarItensdosDocumentosFiscais = field.NewBool(tableName, "InformarItensdosDocumentosFiscais")
	_loja.CorPrimaria = field.NewString(tableName, "CorPrimaria")
	_loja.CorSecundaria = field.NewString(tableName, "CorSecundaria")
	_loja.TituloSite = field.NewString(tableName, "TituloSite")
	_loja.RodapeSite = field.NewString(tableName, "RodapeSite")
	_loja.DescontoMaximoDinheiro = field.NewFloat64(tableName, "DescontoMaximoDinheiro")
	_loja.DescontoMaximoCartao = field.NewFloat64(tableName, "DescontoMaximoCartao")
	_loja.ChavePIX = field.NewString(tableName, "ChavePIX")

	_loja.fillFieldMap()

	return _loja
}

type loja struct {
	lojaDo lojaDo

	ALL                                   field.Asterisk
	Codigo                                field.Int64
	RazaoSocial                           field.String
	Fantasia                              field.String
	Endereco                              field.String
	CEP                                   field.String
	Bairro                                field.String
	UF                                    field.String
	Cidade                                field.String
	Fone                                  field.String
	Fax                                   field.String
	CNPJ                                  field.String
	CGF                                   field.String
	Contato                               field.String
	Celular                               field.String
	DataCadastro                          field.Time
	Tabela                                field.Int64
	Email                                 field.String
	Franquia                              field.Bool
	Regime                                field.Bool
	TipodaLoja                            field.Int64
	Senha                                 field.String
	SenhaSupervisor                       field.String
	MetaDiariaValor                       field.Field
	MetaDiariaPecas                       field.Int64
	InativarClienteAposMesesSemComprar    field.Int64
	Arredondamento                        field.Field
	DescontoMaximo                        field.Field
	DescontoMaximoFuncionario             field.Field
	DescontosemCorretor                   field.Float64
	MinimoparaAtacadoValor                field.Int64
	QtdepcAtacado                         field.Int64
	PercentuaMaximodeRetornodeConsignacao field.Int64
	MensagemparaComandadeVenda            field.String
	PadraoComanda                         field.Int64
	CodigoNomeEmpresaACFiscal             field.String
	CodigoParticipanteACFiscal            field.Int64
	EnviarICMSArquivoFortes               field.Bool
	Inativo                               field.Bool
	ObsRegime1                            field.String
	ObsRegime2                            field.String
	ObsRegime3                            field.String
	ObsRegime4                            field.String
	CSTPIS                                field.String
	CSTCOFINS                             field.String
	AliquotaPIS                           field.Float64
	AliquotaCOFINS                        field.Float64
	SerieCertificadoDigital               field.String
	CaminhoLogotipoDanfe                  field.String
	CSTICMS                               field.String
	CNPJCPFCertificadoDigital             field.String
	RegimeTributario                      field.Int64
	CSOSN                                 field.Int64
	UtilizarAliquotaICMSCadastroCFOP      field.Bool
	NFeAmbiente                           field.String
	NFeAtivaTrace                         field.String
	NFeCNPJ                               field.String
	NFeContigencia                        field.String
	NFeDanfeInfo                          field.String
	NFeDanfeLogo                          field.String
	NFeDataPacket                         field.String
	NFeDataPacketFormSeg                  field.String
	NFeModelo                             field.String
	NFeCancelamento                       field.String
	NFeConsultaCadastro                   field.String
	NFeConsultaProtocolo                  field.String
	NFeInutilizacao                       field.String
	NFeRecepcao                           field.String
	NFeRetRecepcao                        field.String
	NFeStatusServico                      field.String
	NFeNoSerieCertificado                 field.String
	NFePathPrincipal                      field.String
	NFeSchemas                            field.String
	NFeSerie                              field.String
	NFeTipoDanfe                          field.String
	NFeTotalizarCfop                      field.String
	NFeUnidadeFederada                    field.String
	NFeUnidadeFederadaCodigo              field.String
	NFeVerProc                            field.String
	NFeEmail                              field.String
	NFeNomeExibicaoEmail                  field.String
	NFeSenhaEmail                         field.String
	NFeServidorSMTPEmail                  field.String
	NFeSSLEmail                           field.String
	NFeHostProxy                          field.String
	NFePortaProxy                         field.String
	NFeSenhaProxy                         field.String
	NFeUsuarioProxy                       field.String
	MensagemparacomandadeConsignacao      field.String
	Gerente                               field.Int64
	CodigoEstabelecimentoACFiscal         field.Int64
	NFeRecepcaoEvento                     field.String
	NFeDanfeCanhoto                       field.String
	NFeDanfeTpDesc                        field.String
	NFeFormatoItemQtd                     field.String
	NFeFormatoItemUnt                     field.String
	NFeSizeFontObs                        field.String
	NFeValASS                             field.String
	NFeValMD5                             field.String
	PRPercentual                          field.Float64
	PRQtdeDiasLimite                      field.Int64
	PRQtdeVendaPremiar                    field.Int64
	UtilizaPremiacaoCorretor              field.Bool
	InformarPISCOFINSArquivoFortes        field.Bool
	AddMensVendaNoOrcamento               field.Bool
	DescontoMaximoVarejo                  field.Int64
	ObrigaTelefoneCliente                 field.Bool
	NFeAutorizacao                        field.String
	NFeRetAutorizacao                     field.String
	ImprimeVendaBobina                    field.Bool
	LojaOnLine                            field.Bool
	NFCeAmbiente                          field.Int64
	NFCeModelo                            field.Int64
	NFCePathPrincipal                     field.String
	NFCeSerie                             field.Int64
	NFCeTipoDanfe                         field.Int64
	NFCeVersaoXML                         field.String
	CalculaTributosAproximados            field.Bool
	DescontoSuframa                       field.Float64
	DataFinalPeriodoBase                  field.Time
	SaldoICMS                             field.Field
	SaldoICMSTipo                         field.String
	SaldoIPI                              field.Field
	SaldoIPITipo                          field.String
	SaldoCOFINS                           field.Field
	SaldoCOFINSTipo                       field.String
	SaldoPIS                              field.Field
	SaldoPISTipo                          field.String
	Numero                                field.String
	CodigoContabilista                    field.Int64
	InformarItensdosDocumentosFiscais     field.Bool
	CorPrimaria                           field.String
	CorSecundaria                         field.String
	TituloSite                            field.String
	RodapeSite                            field.String
	DescontoMaximoDinheiro                field.Float64
	DescontoMaximoCartao                  field.Float64
	ChavePIX                              field.String

	fieldMap map[string]field.Expr
}

func (l loja) Table(newTableName string) *loja {
	l.lojaDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l loja) As(alias string) *loja {
	l.lojaDo.DO = *(l.lojaDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *loja) updateTableName(table string) *loja {
	l.ALL = field.NewAsterisk(table)
	l.Codigo = field.NewInt64(table, "Codigo")
	l.RazaoSocial = field.NewString(table, "RazaoSocial")
	l.Fantasia = field.NewString(table, "Fantasia")
	l.Endereco = field.NewString(table, "Endereco")
	l.CEP = field.NewString(table, "CEP")
	l.Bairro = field.NewString(table, "Bairro")
	l.UF = field.NewString(table, "UF")
	l.Cidade = field.NewString(table, "Cidade")
	l.Fone = field.NewString(table, "Fone")
	l.Fax = field.NewString(table, "Fax")
	l.CNPJ = field.NewString(table, "CNPJ")
	l.CGF = field.NewString(table, "CGF")
	l.Contato = field.NewString(table, "Contato")
	l.Celular = field.NewString(table, "Celular")
	l.DataCadastro = field.NewTime(table, "DataCadastro")
	l.Tabela = field.NewInt64(table, "Tabela")
	l.Email = field.NewString(table, "Email")
	l.Franquia = field.NewBool(table, "Franquia")
	l.Regime = field.NewBool(table, "Regime")
	l.TipodaLoja = field.NewInt64(table, "TipodaLoja")
	l.Senha = field.NewString(table, "Senha")
	l.SenhaSupervisor = field.NewString(table, "SenhaSupervisor")
	l.MetaDiariaValor = field.NewField(table, "MetaDiariaValor")
	l.MetaDiariaPecas = field.NewInt64(table, "MetaDiariaPecas")
	l.InativarClienteAposMesesSemComprar = field.NewInt64(table, "InativarClienteAposMesesSemComprar")
	l.Arredondamento = field.NewField(table, "Arredondamento")
	l.DescontoMaximo = field.NewField(table, "DescontoMaximo")
	l.DescontoMaximoFuncionario = field.NewField(table, "DescontoMaximoFuncionario")
	l.DescontosemCorretor = field.NewFloat64(table, "DescontosemCorretor")
	l.MinimoparaAtacadoValor = field.NewInt64(table, "MinimoparaAtacadoValor")
	l.QtdepcAtacado = field.NewInt64(table, "QtdepcAtacado")
	l.PercentuaMaximodeRetornodeConsignacao = field.NewInt64(table, "PercentuaMaximodeRetornodeConsignacao")
	l.MensagemparaComandadeVenda = field.NewString(table, "MensagemparaComandadeVenda")
	l.PadraoComanda = field.NewInt64(table, "PadraoComanda")
	l.CodigoNomeEmpresaACFiscal = field.NewString(table, "CodigoNomeEmpresaACFiscal")
	l.CodigoParticipanteACFiscal = field.NewInt64(table, "CodigoParticipanteACFiscal")
	l.EnviarICMSArquivoFortes = field.NewBool(table, "EnviarICMSArquivoFortes")
	l.Inativo = field.NewBool(table, "Inativo")
	l.ObsRegime1 = field.NewString(table, "ObsRegime1")
	l.ObsRegime2 = field.NewString(table, "ObsRegime2")
	l.ObsRegime3 = field.NewString(table, "ObsRegime3")
	l.ObsRegime4 = field.NewString(table, "ObsRegime4")
	l.CSTPIS = field.NewString(table, "CST_PIS")
	l.CSTCOFINS = field.NewString(table, "CST_COFINS")
	l.AliquotaPIS = field.NewFloat64(table, "Aliquota_PIS")
	l.AliquotaCOFINS = field.NewFloat64(table, "Aliquota_COFINS")
	l.SerieCertificadoDigital = field.NewString(table, "SerieCertificadoDigital")
	l.CaminhoLogotipoDanfe = field.NewString(table, "CaminhoLogotipoDanfe")
	l.CSTICMS = field.NewString(table, "CST_ICMS")
	l.CNPJCPFCertificadoDigital = field.NewString(table, "CNPJCPFCertificadoDigital")
	l.RegimeTributario = field.NewInt64(table, "RegimeTributario")
	l.CSOSN = field.NewInt64(table, "CSOSN")
	l.UtilizarAliquotaICMSCadastroCFOP = field.NewBool(table, "UtilizarAliquotaICMSCadastroCFOP")
	l.NFeAmbiente = field.NewString(table, "NFeAmbiente")
	l.NFeAtivaTrace = field.NewString(table, "NFeAtivaTrace")
	l.NFeCNPJ = field.NewString(table, "NFeCNPJ")
	l.NFeContigencia = field.NewString(table, "NFeContigencia")
	l.NFeDanfeInfo = field.NewString(table, "NFeDanfeInfo")
	l.NFeDanfeLogo = field.NewString(table, "NFeDanfeLogo")
	l.NFeDataPacket = field.NewString(table, "NFeDataPacket")
	l.NFeDataPacketFormSeg = field.NewString(table, "NFeDataPacketFormSeg")
	l.NFeModelo = field.NewString(table, "NFeModelo")
	l.NFeCancelamento = field.NewString(table, "NFeCancelamento")
	l.NFeConsultaCadastro = field.NewString(table, "NFeConsultaCadastro")
	l.NFeConsultaProtocolo = field.NewString(table, "NFeConsultaProtocolo")
	l.NFeInutilizacao = field.NewString(table, "NFeInutilizacao")
	l.NFeRecepcao = field.NewString(table, "NFeRecepcao")
	l.NFeRetRecepcao = field.NewString(table, "NFeRetRecepcao")
	l.NFeStatusServico = field.NewString(table, "NFeStatusServico")
	l.NFeNoSerieCertificado = field.NewString(table, "NFeNoSerieCertificado")
	l.NFePathPrincipal = field.NewString(table, "NFePathPrincipal")
	l.NFeSchemas = field.NewString(table, "NFeSchemas")
	l.NFeSerie = field.NewString(table, "NFeSerie")
	l.NFeTipoDanfe = field.NewString(table, "NFeTipoDanfe")
	l.NFeTotalizarCfop = field.NewString(table, "NFeTotalizarCfop")
	l.NFeUnidadeFederada = field.NewString(table, "NFeUnidadeFederada")
	l.NFeUnidadeFederadaCodigo = field.NewString(table, "NFeUnidadeFederadaCodigo")
	l.NFeVerProc = field.NewString(table, "NFeVerProc")
	l.NFeEmail = field.NewString(table, "NFeEmail")
	l.NFeNomeExibicaoEmail = field.NewString(table, "NFeNomeExibicaoEmail")
	l.NFeSenhaEmail = field.NewString(table, "NFeSenhaEmail")
	l.NFeServidorSMTPEmail = field.NewString(table, "NFeServidorSMTPEmail")
	l.NFeSSLEmail = field.NewString(table, "NFeSSLEmail")
	l.NFeHostProxy = field.NewString(table, "NFeHostProxy")
	l.NFePortaProxy = field.NewString(table, "NFePortaProxy")
	l.NFeSenhaProxy = field.NewString(table, "NFeSenhaProxy")
	l.NFeUsuarioProxy = field.NewString(table, "NFeUsuarioProxy")
	l.MensagemparacomandadeConsignacao = field.NewString(table, "MensagemparacomandadeConsignacao")
	l.Gerente = field.NewInt64(table, "Gerente")
	l.CodigoEstabelecimentoACFiscal = field.NewInt64(table, "CodigoEstabelecimentoACFiscal")
	l.NFeRecepcaoEvento = field.NewString(table, "NFeRecepcaoEvento")
	l.NFeDanfeCanhoto = field.NewString(table, "NFeDanfeCanhoto")
	l.NFeDanfeTpDesc = field.NewString(table, "NFeDanfeTpDesc")
	l.NFeFormatoItemQtd = field.NewString(table, "NFeFormatoItemQtd")
	l.NFeFormatoItemUnt = field.NewString(table, "NFeFormatoItemUnt")
	l.NFeSizeFontObs = field.NewString(table, "NFeSizeFontObs")
	l.NFeValASS = field.NewString(table, "NFeVal_ASS")
	l.NFeValMD5 = field.NewString(table, "NFeVal_MD5")
	l.PRPercentual = field.NewFloat64(table, "PRPercentual")
	l.PRQtdeDiasLimite = field.NewInt64(table, "PRQtdeDiasLimite")
	l.PRQtdeVendaPremiar = field.NewInt64(table, "PRQtdeVendaPremiar")
	l.UtilizaPremiacaoCorretor = field.NewBool(table, "UtilizaPremiacaoCorretor")
	l.InformarPISCOFINSArquivoFortes = field.NewBool(table, "InformarPISCOFINSArquivoFortes")
	l.AddMensVendaNoOrcamento = field.NewBool(table, "addMensVendaNoOrcamento")
	l.DescontoMaximoVarejo = field.NewInt64(table, "DescontoMaximoVarejo")
	l.ObrigaTelefoneCliente = field.NewBool(table, "ObrigaTelefoneCliente")
	l.NFeAutorizacao = field.NewString(table, "NFeAutorizacao")
	l.NFeRetAutorizacao = field.NewString(table, "NFeRetAutorizacao")
	l.ImprimeVendaBobina = field.NewBool(table, "ImprimeVendaBobina")
	l.LojaOnLine = field.NewBool(table, "LojaOnLine")
	l.NFCeAmbiente = field.NewInt64(table, "NFCeAmbiente")
	l.NFCeModelo = field.NewInt64(table, "NFCeModelo")
	l.NFCePathPrincipal = field.NewString(table, "NFCePathPrincipal")
	l.NFCeSerie = field.NewInt64(table, "NFCeSerie")
	l.NFCeTipoDanfe = field.NewInt64(table, "NFCeTipoDanfe")
	l.NFCeVersaoXML = field.NewString(table, "NFCeVersaoXML")
	l.CalculaTributosAproximados = field.NewBool(table, "CalculaTributosAproximados")
	l.DescontoSuframa = field.NewFloat64(table, "DescontoSuframa")
	l.DataFinalPeriodoBase = field.NewTime(table, "DataFinalPeriodoBase")
	l.SaldoICMS = field.NewField(table, "SaldoICMS")
	l.SaldoICMSTipo = field.NewString(table, "SaldoICMS_Tipo")
	l.SaldoIPI = field.NewField(table, "SaldoIPI")
	l.SaldoIPITipo = field.NewString(table, "SaldoIPI_Tipo")
	l.SaldoCOFINS = field.NewField(table, "SaldoCOFINS")
	l.SaldoCOFINSTipo = field.NewString(table, "SaldoCOFINS_Tipo")
	l.SaldoPIS = field.NewField(table, "SaldoPIS")
	l.SaldoPISTipo = field.NewString(table, "SaldoPIS_Tipo")
	l.Numero = field.NewString(table, "Numero")
	l.CodigoContabilista = field.NewInt64(table, "CodigoContabilista")
	l.InformarItensdosDocumentosFiscais = field.NewBool(table, "InformarItensdosDocumentosFiscais")
	l.CorPrimaria = field.NewString(table, "CorPrimaria")
	l.CorSecundaria = field.NewString(table, "CorSecundaria")
	l.TituloSite = field.NewString(table, "TituloSite")
	l.RodapeSite = field.NewString(table, "RodapeSite")
	l.DescontoMaximoDinheiro = field.NewFloat64(table, "DescontoMaximoDinheiro")
	l.DescontoMaximoCartao = field.NewFloat64(table, "DescontoMaximoCartao")
	l.ChavePIX = field.NewString(table, "ChavePIX")

	l.fillFieldMap()

	return l
}

func (l *loja) WithContext(ctx context.Context) *lojaDo { return l.lojaDo.WithContext(ctx) }

func (l loja) TableName() string { return l.lojaDo.TableName() }

func (l loja) Alias() string { return l.lojaDo.Alias() }

func (l loja) Columns(cols ...field.Expr) gen.Columns { return l.lojaDo.Columns(cols...) }

func (l *loja) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *loja) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 137)
	l.fieldMap["Codigo"] = l.Codigo
	l.fieldMap["RazaoSocial"] = l.RazaoSocial
	l.fieldMap["Fantasia"] = l.Fantasia
	l.fieldMap["Endereco"] = l.Endereco
	l.fieldMap["CEP"] = l.CEP
	l.fieldMap["Bairro"] = l.Bairro
	l.fieldMap["UF"] = l.UF
	l.fieldMap["Cidade"] = l.Cidade
	l.fieldMap["Fone"] = l.Fone
	l.fieldMap["Fax"] = l.Fax
	l.fieldMap["CNPJ"] = l.CNPJ
	l.fieldMap["CGF"] = l.CGF
	l.fieldMap["Contato"] = l.Contato
	l.fieldMap["Celular"] = l.Celular
	l.fieldMap["DataCadastro"] = l.DataCadastro
	l.fieldMap["Tabela"] = l.Tabela
	l.fieldMap["Email"] = l.Email
	l.fieldMap["Franquia"] = l.Franquia
	l.fieldMap["Regime"] = l.Regime
	l.fieldMap["TipodaLoja"] = l.TipodaLoja
	l.fieldMap["Senha"] = l.Senha
	l.fieldMap["SenhaSupervisor"] = l.SenhaSupervisor
	l.fieldMap["MetaDiariaValor"] = l.MetaDiariaValor
	l.fieldMap["MetaDiariaPecas"] = l.MetaDiariaPecas
	l.fieldMap["InativarClienteAposMesesSemComprar"] = l.InativarClienteAposMesesSemComprar
	l.fieldMap["Arredondamento"] = l.Arredondamento
	l.fieldMap["DescontoMaximo"] = l.DescontoMaximo
	l.fieldMap["DescontoMaximoFuncionario"] = l.DescontoMaximoFuncionario
	l.fieldMap["DescontosemCorretor"] = l.DescontosemCorretor
	l.fieldMap["MinimoparaAtacadoValor"] = l.MinimoparaAtacadoValor
	l.fieldMap["QtdepcAtacado"] = l.QtdepcAtacado
	l.fieldMap["PercentuaMaximodeRetornodeConsignacao"] = l.PercentuaMaximodeRetornodeConsignacao
	l.fieldMap["MensagemparaComandadeVenda"] = l.MensagemparaComandadeVenda
	l.fieldMap["PadraoComanda"] = l.PadraoComanda
	l.fieldMap["CodigoNomeEmpresaACFiscal"] = l.CodigoNomeEmpresaACFiscal
	l.fieldMap["CodigoParticipanteACFiscal"] = l.CodigoParticipanteACFiscal
	l.fieldMap["EnviarICMSArquivoFortes"] = l.EnviarICMSArquivoFortes
	l.fieldMap["Inativo"] = l.Inativo
	l.fieldMap["ObsRegime1"] = l.ObsRegime1
	l.fieldMap["ObsRegime2"] = l.ObsRegime2
	l.fieldMap["ObsRegime3"] = l.ObsRegime3
	l.fieldMap["ObsRegime4"] = l.ObsRegime4
	l.fieldMap["CST_PIS"] = l.CSTPIS
	l.fieldMap["CST_COFINS"] = l.CSTCOFINS
	l.fieldMap["Aliquota_PIS"] = l.AliquotaPIS
	l.fieldMap["Aliquota_COFINS"] = l.AliquotaCOFINS
	l.fieldMap["SerieCertificadoDigital"] = l.SerieCertificadoDigital
	l.fieldMap["CaminhoLogotipoDanfe"] = l.CaminhoLogotipoDanfe
	l.fieldMap["CST_ICMS"] = l.CSTICMS
	l.fieldMap["CNPJCPFCertificadoDigital"] = l.CNPJCPFCertificadoDigital
	l.fieldMap["RegimeTributario"] = l.RegimeTributario
	l.fieldMap["CSOSN"] = l.CSOSN
	l.fieldMap["UtilizarAliquotaICMSCadastroCFOP"] = l.UtilizarAliquotaICMSCadastroCFOP
	l.fieldMap["NFeAmbiente"] = l.NFeAmbiente
	l.fieldMap["NFeAtivaTrace"] = l.NFeAtivaTrace
	l.fieldMap["NFeCNPJ"] = l.NFeCNPJ
	l.fieldMap["NFeContigencia"] = l.NFeContigencia
	l.fieldMap["NFeDanfeInfo"] = l.NFeDanfeInfo
	l.fieldMap["NFeDanfeLogo"] = l.NFeDanfeLogo
	l.fieldMap["NFeDataPacket"] = l.NFeDataPacket
	l.fieldMap["NFeDataPacketFormSeg"] = l.NFeDataPacketFormSeg
	l.fieldMap["NFeModelo"] = l.NFeModelo
	l.fieldMap["NFeCancelamento"] = l.NFeCancelamento
	l.fieldMap["NFeConsultaCadastro"] = l.NFeConsultaCadastro
	l.fieldMap["NFeConsultaProtocolo"] = l.NFeConsultaProtocolo
	l.fieldMap["NFeInutilizacao"] = l.NFeInutilizacao
	l.fieldMap["NFeRecepcao"] = l.NFeRecepcao
	l.fieldMap["NFeRetRecepcao"] = l.NFeRetRecepcao
	l.fieldMap["NFeStatusServico"] = l.NFeStatusServico
	l.fieldMap["NFeNoSerieCertificado"] = l.NFeNoSerieCertificado
	l.fieldMap["NFePathPrincipal"] = l.NFePathPrincipal
	l.fieldMap["NFeSchemas"] = l.NFeSchemas
	l.fieldMap["NFeSerie"] = l.NFeSerie
	l.fieldMap["NFeTipoDanfe"] = l.NFeTipoDanfe
	l.fieldMap["NFeTotalizarCfop"] = l.NFeTotalizarCfop
	l.fieldMap["NFeUnidadeFederada"] = l.NFeUnidadeFederada
	l.fieldMap["NFeUnidadeFederadaCodigo"] = l.NFeUnidadeFederadaCodigo
	l.fieldMap["NFeVerProc"] = l.NFeVerProc
	l.fieldMap["NFeEmail"] = l.NFeEmail
	l.fieldMap["NFeNomeExibicaoEmail"] = l.NFeNomeExibicaoEmail
	l.fieldMap["NFeSenhaEmail"] = l.NFeSenhaEmail
	l.fieldMap["NFeServidorSMTPEmail"] = l.NFeServidorSMTPEmail
	l.fieldMap["NFeSSLEmail"] = l.NFeSSLEmail
	l.fieldMap["NFeHostProxy"] = l.NFeHostProxy
	l.fieldMap["NFePortaProxy"] = l.NFePortaProxy
	l.fieldMap["NFeSenhaProxy"] = l.NFeSenhaProxy
	l.fieldMap["NFeUsuarioProxy"] = l.NFeUsuarioProxy
	l.fieldMap["MensagemparacomandadeConsignacao"] = l.MensagemparacomandadeConsignacao
	l.fieldMap["Gerente"] = l.Gerente
	l.fieldMap["CodigoEstabelecimentoACFiscal"] = l.CodigoEstabelecimentoACFiscal
	l.fieldMap["NFeRecepcaoEvento"] = l.NFeRecepcaoEvento
	l.fieldMap["NFeDanfeCanhoto"] = l.NFeDanfeCanhoto
	l.fieldMap["NFeDanfeTpDesc"] = l.NFeDanfeTpDesc
	l.fieldMap["NFeFormatoItemQtd"] = l.NFeFormatoItemQtd
	l.fieldMap["NFeFormatoItemUnt"] = l.NFeFormatoItemUnt
	l.fieldMap["NFeSizeFontObs"] = l.NFeSizeFontObs
	l.fieldMap["NFeVal_ASS"] = l.NFeValASS
	l.fieldMap["NFeVal_MD5"] = l.NFeValMD5
	l.fieldMap["PRPercentual"] = l.PRPercentual
	l.fieldMap["PRQtdeDiasLimite"] = l.PRQtdeDiasLimite
	l.fieldMap["PRQtdeVendaPremiar"] = l.PRQtdeVendaPremiar
	l.fieldMap["UtilizaPremiacaoCorretor"] = l.UtilizaPremiacaoCorretor
	l.fieldMap["InformarPISCOFINSArquivoFortes"] = l.InformarPISCOFINSArquivoFortes
	l.fieldMap["addMensVendaNoOrcamento"] = l.AddMensVendaNoOrcamento
	l.fieldMap["DescontoMaximoVarejo"] = l.DescontoMaximoVarejo
	l.fieldMap["ObrigaTelefoneCliente"] = l.ObrigaTelefoneCliente
	l.fieldMap["NFeAutorizacao"] = l.NFeAutorizacao
	l.fieldMap["NFeRetAutorizacao"] = l.NFeRetAutorizacao
	l.fieldMap["ImprimeVendaBobina"] = l.ImprimeVendaBobina
	l.fieldMap["LojaOnLine"] = l.LojaOnLine
	l.fieldMap["NFCeAmbiente"] = l.NFCeAmbiente
	l.fieldMap["NFCeModelo"] = l.NFCeModelo
	l.fieldMap["NFCePathPrincipal"] = l.NFCePathPrincipal
	l.fieldMap["NFCeSerie"] = l.NFCeSerie
	l.fieldMap["NFCeTipoDanfe"] = l.NFCeTipoDanfe
	l.fieldMap["NFCeVersaoXML"] = l.NFCeVersaoXML
	l.fieldMap["CalculaTributosAproximados"] = l.CalculaTributosAproximados
	l.fieldMap["DescontoSuframa"] = l.DescontoSuframa
	l.fieldMap["DataFinalPeriodoBase"] = l.DataFinalPeriodoBase
	l.fieldMap["SaldoICMS"] = l.SaldoICMS
	l.fieldMap["SaldoICMS_Tipo"] = l.SaldoICMSTipo
	l.fieldMap["SaldoIPI"] = l.SaldoIPI
	l.fieldMap["SaldoIPI_Tipo"] = l.SaldoIPITipo
	l.fieldMap["SaldoCOFINS"] = l.SaldoCOFINS
	l.fieldMap["SaldoCOFINS_Tipo"] = l.SaldoCOFINSTipo
	l.fieldMap["SaldoPIS"] = l.SaldoPIS
	l.fieldMap["SaldoPIS_Tipo"] = l.SaldoPISTipo
	l.fieldMap["Numero"] = l.Numero
	l.fieldMap["CodigoContabilista"] = l.CodigoContabilista
	l.fieldMap["InformarItensdosDocumentosFiscais"] = l.InformarItensdosDocumentosFiscais
	l.fieldMap["CorPrimaria"] = l.CorPrimaria
	l.fieldMap["CorSecundaria"] = l.CorSecundaria
	l.fieldMap["TituloSite"] = l.TituloSite
	l.fieldMap["RodapeSite"] = l.RodapeSite
	l.fieldMap["DescontoMaximoDinheiro"] = l.DescontoMaximoDinheiro
	l.fieldMap["DescontoMaximoCartao"] = l.DescontoMaximoCartao
	l.fieldMap["ChavePIX"] = l.ChavePIX
}

func (l loja) clone(db *gorm.DB) loja {
	l.lojaDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l loja) replaceDB(db *gorm.DB) loja {
	l.lojaDo.ReplaceDB(db)
	return l
}

type lojaDo struct{ gen.DO }

func (l lojaDo) Debug() *lojaDo {
	return l.withDO(l.DO.Debug())
}

func (l lojaDo) WithContext(ctx context.Context) *lojaDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lojaDo) ReadDB() *lojaDo {
	return l.Clauses(dbresolver.Read)
}

func (l lojaDo) WriteDB() *lojaDo {
	return l.Clauses(dbresolver.Write)
}

func (l lojaDo) Session(config *gorm.Session) *lojaDo {
	return l.withDO(l.DO.Session(config))
}

func (l lojaDo) Clauses(conds ...clause.Expression) *lojaDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lojaDo) Returning(value interface{}, columns ...string) *lojaDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lojaDo) Not(conds ...gen.Condition) *lojaDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lojaDo) Or(conds ...gen.Condition) *lojaDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lojaDo) Select(conds ...field.Expr) *lojaDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lojaDo) Where(conds ...gen.Condition) *lojaDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lojaDo) Order(conds ...field.Expr) *lojaDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lojaDo) Distinct(cols ...field.Expr) *lojaDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lojaDo) Omit(cols ...field.Expr) *lojaDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lojaDo) Join(table schema.Tabler, on ...field.Expr) *lojaDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lojaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lojaDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lojaDo) RightJoin(table schema.Tabler, on ...field.Expr) *lojaDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lojaDo) Group(cols ...field.Expr) *lojaDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lojaDo) Having(conds ...gen.Condition) *lojaDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lojaDo) Limit(limit int) *lojaDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lojaDo) Offset(offset int) *lojaDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lojaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lojaDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lojaDo) Unscoped() *lojaDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lojaDo) Create(values ...*model.Loja) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lojaDo) CreateInBatches(values []*model.Loja, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lojaDo) Save(values ...*model.Loja) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lojaDo) First() (*model.Loja, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Loja), nil
	}
}

func (l lojaDo) Take() (*model.Loja, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Loja), nil
	}
}

func (l lojaDo) Last() (*model.Loja, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Loja), nil
	}
}

func (l lojaDo) Find() ([]*model.Loja, error) {
	result, err := l.DO.Find()
	return result.([]*model.Loja), err
}

func (l lojaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Loja, err error) {
	buf := make([]*model.Loja, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lojaDo) FindInBatches(result *[]*model.Loja, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lojaDo) Attrs(attrs ...field.AssignExpr) *lojaDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lojaDo) Assign(attrs ...field.AssignExpr) *lojaDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lojaDo) Joins(fields ...field.RelationField) *lojaDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lojaDo) Preload(fields ...field.RelationField) *lojaDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lojaDo) FirstOrInit() (*model.Loja, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Loja), nil
	}
}

func (l lojaDo) FirstOrCreate() (*model.Loja, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Loja), nil
	}
}

func (l lojaDo) FindByPage(offset int, limit int) (result []*model.Loja, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lojaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lojaDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lojaDo) Delete(models ...*model.Loja) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lojaDo) withDO(do gen.Dao) *lojaDo {
	l.DO = *do.(*gen.DO)
	return l
}
