// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComandasItem = "Comandas_Item"

// ComandasItem mapped from table <Comandas_Item>
type ComandasItem struct {
	Comanda               int64   `gorm:"column:Comanda;primaryKey" json:"Comanda"`
	Produto               string  `gorm:"column:Produto;primaryKey" json:"Produto"`
	Item                  int64   `gorm:"column:Item;primaryKey" json:"Item"`
	Qtde                  int64   `gorm:"column:Qtde;not null" json:"Qtde"`
	Unitario              []uint8 `gorm:"column:Unitario;not null;default:0" json:"Unitario"`
	Total                 []uint8 `gorm:"column:Total;not null;default:0" json:"Total"`
	Promocao              int64   `gorm:"column:Promocao;not null" json:"Promocao"`
	Cor                   int64   `gorm:"column:Cor;not null" json:"Cor"`
	Tam                   string  `gorm:"column:Tam" json:"Tam"`
	Posicao               int64   `gorm:"column:Posicao;not null" json:"Posicao"`
	PecacomLD             int64   `gorm:"column:PecacomLD;not null" json:"PecacomLD"`
	SituacaoTributariaECF string  `gorm:"column:SituacaoTributariaECF" json:"SituacaoTributariaECF"`
	ValorDescontoProduto  []uint8 `gorm:"column:ValorDescontoProduto;default:0" json:"ValorDescontoProduto"`
	Unidade               string  `gorm:"column:Unidade" json:"Unidade"`
	CFOP                  int64   `gorm:"column:CFOP" json:"CFOP"`
	CstICMS               string  `gorm:"column:CstICMS" json:"CstICMS"`
	AliquotaICMS          float64 `gorm:"column:AliquotaICMS" json:"AliquotaICMS"`
	CstPis                string  `gorm:"column:CstPis" json:"CstPis"`
	AliquotaPis           float64 `gorm:"column:AliquotaPis" json:"AliquotaPis"`
	CstCofins             string  `gorm:"column:CstCofins" json:"CstCofins"`
	AliquotaCofins        float64 `gorm:"column:AliquotaCofins" json:"AliquotaCofins"`
}

// TableName ComandasItem's table name
func (*ComandasItem) TableName() string {
	return TableNameComandasItem
}
