// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComandasItemGrade = "Comandas_ItemGrade"

// ComandasItemGrade mapped from table <Comandas_ItemGrade>
type ComandasItemGrade struct {
	Comanda int64  `gorm:"column:Comanda;primaryKey" json:"Comanda"`
	Produto string `gorm:"column:Produto;primaryKey" json:"Produto"`
	Cor     int64  `gorm:"column:Cor;primaryKey" json:"Cor"`
	Tam01   int64  `gorm:"column:Tam01;not null" json:"Tam01"`
	Tam02   int64  `gorm:"column:Tam02;not null" json:"Tam02"`
	Tam03   int64  `gorm:"column:Tam03;not null" json:"Tam03"`
	Tam04   int64  `gorm:"column:Tam04;not null" json:"Tam04"`
	Tam05   int64  `gorm:"column:Tam05;not null" json:"Tam05"`
	Tam06   int64  `gorm:"column:Tam06;not null" json:"Tam06"`
	Tam07   int64  `gorm:"column:Tam07;not null" json:"Tam07"`
	Tam08   int64  `gorm:"column:Tam08;not null" json:"Tam08"`
	Tam09   int64  `gorm:"column:Tam09;not null" json:"Tam09"`
	Tam10   int64  `gorm:"column:Tam10;not null" json:"Tam10"`
}

// TableName ComandasItemGrade's table name
func (*ComandasItemGrade) TableName() string {
	return TableNameComandasItemGrade
}
