// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEmpresa = "Empresa"

// Empresa mapped from table <Empresa>
type Empresa struct {
	Codigo                          int64  `gorm:"column:Codigo;primaryKey" json:"Codigo"`
	RazaoSocial                     string `gorm:"column:RazaoSocial" json:"RazaoSocial"`
	Fantasia                        string `gorm:"column:Fantasia" json:"Fantasia"`
	Endereco                        string `gorm:"column:Endereco" json:"Endereco"`
	CEP                             string `gorm:"column:CEP" json:"CEP"`
	Bairro                          string `gorm:"column:Bairro" json:"Bairro"`
	UF                              string `gorm:"column:UF" json:"UF"`
	Cidade                          string `gorm:"column:Cidade" json:"Cidade"`
	CNPJCPF                         string `gorm:"column:CNPJCPF" json:"CNPJCPF"`
	CGFRG                           string `gorm:"column:CGFRG" json:"CGFRG"`
	Email                           string `gorm:"column:Email" json:"Email"`
	Fone                            string `gorm:"column:Fone" json:"Fone"`
	Fax                             string `gorm:"column:Fax" json:"Fax"`
	ImprimirDuplicatacomoNumerodaNF bool   `gorm:"column:ImprimirDuplicatacomoNumerodaNF;not null;default:0" json:"ImprimirDuplicatacomoNumerodaNF"`
	CNPJResponsavelTecnico          string `gorm:"column:CNPJResponsavelTecnico" json:"CNPJResponsavelTecnico"`
	ContatoResponsavelTecnico       string `gorm:"column:ContatoResponsavelTecnico" json:"ContatoResponsavelTecnico"`
	EmailResponsavelTecnico         string `gorm:"column:EmailResponsavelTecnico" json:"EmailResponsavelTecnico"`
	FoneResponsavelTecnico          string `gorm:"column:FoneResponsavelTecnico" json:"FoneResponsavelTecnico"`
}

// TableName Empresa's table name
func (*Empresa) TableName() string {
	return TableNameEmpresa
}
