// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGrupo = "Grupos"

// Grupo mapped from table <Grupos>
type Grupo struct {
	Codigo        int64   `gorm:"column:Codigo;primaryKey" json:"Codigo"`
	Descricao     string  `gorm:"column:Descricao" json:"Descricao"`
	Und           string  `gorm:"column:Und" json:"Und"`
	Valor         []uint8 `gorm:"column:Valor;not null;default:0" json:"Valor"`
	Almox         bool    `gorm:"column:Almox;not null" json:"Almox"`
	DPA           bool    `gorm:"column:DPA;not null" json:"DPA"`
	EstoqueMinimo int64   `gorm:"column:EstoqueMinimo;not null" json:"EstoqueMinimo"`
	EstoqueMaximo int64   `gorm:"column:EstoqueMaximo;not null" json:"EstoqueMaximo"`
	Servico       bool    `gorm:"column:Servico;not null;default:0" json:"Servico"`
}

// TableName Grupo's table name
func (*Grupo) TableName() string {
	return TableNameGrupo
}
