// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLoja = "Lojas"

// Loja mapped from table <Lojas>
type Loja struct {
	Codigo                                int64     `gorm:"column:Codigo;primaryKey" json:"Codigo"`
	RazaoSocial                           string    `gorm:"column:RazaoSocial" json:"RazaoSocial"`
	Fantasia                              string    `gorm:"column:Fantasia" json:"Fantasia"`
	Endereco                              string    `gorm:"column:Endereco" json:"Endereco"`
	CEP                                   string    `gorm:"column:CEP" json:"CEP"`
	Bairro                                string    `gorm:"column:Bairro" json:"Bairro"`
	UF                                    string    `gorm:"column:UF" json:"UF"`
	Cidade                                string    `gorm:"column:Cidade" json:"Cidade"`
	Fone                                  string    `gorm:"column:Fone" json:"Fone"`
	Fax                                   string    `gorm:"column:Fax" json:"Fax"`
	CNPJ                                  string    `gorm:"column:CNPJ" json:"CNPJ"`
	CGF                                   string    `gorm:"column:CGF" json:"CGF"`
	Contato                               string    `gorm:"column:Contato" json:"Contato"`
	Celular                               string    `gorm:"column:Celular" json:"Celular"`
	DataCadastro                          time.Time `gorm:"column:DataCadastro" json:"DataCadastro"`
	Tabela                                int64     `gorm:"column:Tabela;not null;default:1" json:"Tabela"`
	Email                                 string    `gorm:"column:Email" json:"Email"`
	Franquia                              bool      `gorm:"column:Franquia;not null;default:0" json:"Franquia"`
	Regime                                bool      `gorm:"column:Regime;not null;default:0" json:"Regime"`
	TipodaLoja                            int64     `gorm:"column:TipodaLoja;not null" json:"TipodaLoja"`
	Senha                                 string    `gorm:"column:Senha" json:"Senha"`
	SenhaSupervisor                       string    `gorm:"column:SenhaSupervisor" json:"SenhaSupervisor"`
	MetaDiariaValor                       []uint8   `gorm:"column:MetaDiariaValor;not null;default:0" json:"MetaDiariaValor"`
	MetaDiariaPecas                       int64     `gorm:"column:MetaDiariaPecas;not null" json:"MetaDiariaPecas"`
	InativarClienteAposMesesSemComprar    int64     `gorm:"column:InativarClienteAposMesesSemComprar;not null" json:"InativarClienteAposMesesSemComprar"`
	Arredondamento                        []uint8   `gorm:"column:Arredondamento;not null;default:0" json:"Arredondamento"`
	DescontoMaximo                        []uint8   `gorm:"column:DescontoMaximo;not null;default:0" json:"DescontoMaximo"`
	DescontoMaximoFuncionario             []uint8   `gorm:"column:DescontoMaximoFuncionario;not null;default:0" json:"DescontoMaximoFuncionario"`
	DescontosemCorretor                   float64   `gorm:"column:DescontosemCorretor;not null" json:"DescontosemCorretor"`
	MinimoparaAtacadoValor                int64     `gorm:"column:MinimoparaAtacadoValor;not null" json:"MinimoparaAtacadoValor"`
	QtdepcAtacado                         int64     `gorm:"column:QtdepcAtacado;not null" json:"QtdepcAtacado"`
	PercentuaMaximodeRetornodeConsignacao int64     `gorm:"column:PercentuaMaximodeRetornodeConsignacao;not null" json:"PercentuaMaximodeRetornodeConsignacao"`
	MensagemparaComandadeVenda            string    `gorm:"column:MensagemparaComandadeVenda" json:"MensagemparaComandadeVenda"`
	PadraoComanda                         int64     `gorm:"column:PadraoComanda;not null" json:"PadraoComanda"`
	CodigoNomeEmpresaACFiscal             string    `gorm:"column:CodigoNomeEmpresaACFiscal" json:"CodigoNomeEmpresaACFiscal"`
	CodigoParticipanteACFiscal            int64     `gorm:"column:CodigoParticipanteACFiscal;not null" json:"CodigoParticipanteACFiscal"`
	EnviarICMSArquivoFortes               bool      `gorm:"column:EnviarICMSArquivoFortes;not null;default:0" json:"EnviarICMSArquivoFortes"`
	Inativo                               bool      `gorm:"column:Inativo;not null;default:0" json:"Inativo"`
	ObsRegime1                            string    `gorm:"column:ObsRegime1" json:"ObsRegime1"`
	ObsRegime2                            string    `gorm:"column:ObsRegime2" json:"ObsRegime2"`
	ObsRegime3                            string    `gorm:"column:ObsRegime3" json:"ObsRegime3"`
	ObsRegime4                            string    `gorm:"column:ObsRegime4" json:"ObsRegime4"`
	CSTPIS                                string    `gorm:"column:CST_PIS" json:"CST_PIS"`
	CSTCOFINS                             string    `gorm:"column:CST_COFINS" json:"CST_COFINS"`
	AliquotaPIS                           float64   `gorm:"column:Aliquota_PIS;not null" json:"Aliquota_PIS"`
	AliquotaCOFINS                        float64   `gorm:"column:Aliquota_COFINS;not null" json:"Aliquota_COFINS"`
	SerieCertificadoDigital               string    `gorm:"column:SerieCertificadoDigital" json:"SerieCertificadoDigital"`
	CaminhoLogotipoDanfe                  string    `gorm:"column:CaminhoLogotipoDanfe" json:"CaminhoLogotipoDanfe"`
	CSTICMS                               string    `gorm:"column:CST_ICMS" json:"CST_ICMS"`
	CNPJCPFCertificadoDigital             string    `gorm:"column:CNPJCPFCertificadoDigital" json:"CNPJCPFCertificadoDigital"`
	RegimeTributario                      int64     `gorm:"column:RegimeTributario" json:"RegimeTributario"`
	CSOSN                                 int64     `gorm:"column:CSOSN" json:"CSOSN"`
	UtilizarAliquotaICMSCadastroCFOP      bool      `gorm:"column:UtilizarAliquotaICMSCadastroCFOP;not null;default:0" json:"UtilizarAliquotaICMSCadastroCFOP"`
	NFeAmbiente                           string    `gorm:"column:NFeAmbiente" json:"NFeAmbiente"`
	NFeAtivaTrace                         string    `gorm:"column:NFeAtivaTrace" json:"NFeAtivaTrace"`
	NFeCNPJ                               string    `gorm:"column:NFeCNPJ" json:"NFeCNPJ"`
	NFeContigencia                        string    `gorm:"column:NFeContigencia" json:"NFeContigencia"`
	NFeDanfeInfo                          string    `gorm:"column:NFeDanfeInfo" json:"NFeDanfeInfo"`
	NFeDanfeLogo                          string    `gorm:"column:NFeDanfeLogo" json:"NFeDanfeLogo"`
	NFeDataPacket                         string    `gorm:"column:NFeDataPacket" json:"NFeDataPacket"`
	NFeDataPacketFormSeg                  string    `gorm:"column:NFeDataPacketFormSeg" json:"NFeDataPacketFormSeg"`
	NFeModelo                             string    `gorm:"column:NFeModelo" json:"NFeModelo"`
	NFeCancelamento                       string    `gorm:"column:NFeCancelamento" json:"NFeCancelamento"`
	NFeConsultaCadastro                   string    `gorm:"column:NFeConsultaCadastro" json:"NFeConsultaCadastro"`
	NFeConsultaProtocolo                  string    `gorm:"column:NFeConsultaProtocolo" json:"NFeConsultaProtocolo"`
	NFeInutilizacao                       string    `gorm:"column:NFeInutilizacao" json:"NFeInutilizacao"`
	NFeRecepcao                           string    `gorm:"column:NFeRecepcao" json:"NFeRecepcao"`
	NFeRetRecepcao                        string    `gorm:"column:NFeRetRecepcao" json:"NFeRetRecepcao"`
	NFeStatusServico                      string    `gorm:"column:NFeStatusServico" json:"NFeStatusServico"`
	NFeNoSerieCertificado                 string    `gorm:"column:NFeNoSerieCertificado" json:"NFeNoSerieCertificado"`
	NFePathPrincipal                      string    `gorm:"column:NFePathPrincipal" json:"NFePathPrincipal"`
	NFeSchemas                            string    `gorm:"column:NFeSchemas" json:"NFeSchemas"`
	NFeSerie                              string    `gorm:"column:NFeSerie" json:"NFeSerie"`
	NFeTipoDanfe                          string    `gorm:"column:NFeTipoDanfe" json:"NFeTipoDanfe"`
	NFeTotalizarCfop                      string    `gorm:"column:NFeTotalizarCfop" json:"NFeTotalizarCfop"`
	NFeUnidadeFederada                    string    `gorm:"column:NFeUnidadeFederada" json:"NFeUnidadeFederada"`
	NFeUnidadeFederadaCodigo              string    `gorm:"column:NFeUnidadeFederadaCodigo" json:"NFeUnidadeFederadaCodigo"`
	NFeVerProc                            string    `gorm:"column:NFeVerProc" json:"NFeVerProc"`
	NFeEmail                              string    `gorm:"column:NFeEmail" json:"NFeEmail"`
	NFeNomeExibicaoEmail                  string    `gorm:"column:NFeNomeExibicaoEmail" json:"NFeNomeExibicaoEmail"`
	NFeSenhaEmail                         string    `gorm:"column:NFeSenhaEmail" json:"NFeSenhaEmail"`
	NFeServidorSMTPEmail                  string    `gorm:"column:NFeServidorSMTPEmail" json:"NFeServidorSMTPEmail"`
	NFeSSLEmail                           string    `gorm:"column:NFeSSLEmail" json:"NFeSSLEmail"`
	NFeHostProxy                          string    `gorm:"column:NFeHostProxy" json:"NFeHostProxy"`
	NFePortaProxy                         string    `gorm:"column:NFePortaProxy" json:"NFePortaProxy"`
	NFeSenhaProxy                         string    `gorm:"column:NFeSenhaProxy" json:"NFeSenhaProxy"`
	NFeUsuarioProxy                       string    `gorm:"column:NFeUsuarioProxy" json:"NFeUsuarioProxy"`
	MensagemparacomandadeConsignacao      string    `gorm:"column:MensagemparacomandadeConsignacao" json:"MensagemparacomandadeConsignacao"`
	Gerente                               int64     `gorm:"column:Gerente;not null" json:"Gerente"`
	CodigoEstabelecimentoACFiscal         int64     `gorm:"column:CodigoEstabelecimentoACFiscal;not null" json:"CodigoEstabelecimentoACFiscal"`
	NFeRecepcaoEvento                     string    `gorm:"column:NFeRecepcaoEvento" json:"NFeRecepcaoEvento"`
	NFeDanfeCanhoto                       string    `gorm:"column:NFeDanfeCanhoto" json:"NFeDanfeCanhoto"`
	NFeDanfeTpDesc                        string    `gorm:"column:NFeDanfeTpDesc" json:"NFeDanfeTpDesc"`
	NFeFormatoItemQtd                     string    `gorm:"column:NFeFormatoItemQtd" json:"NFeFormatoItemQtd"`
	NFeFormatoItemUnt                     string    `gorm:"column:NFeFormatoItemUnt" json:"NFeFormatoItemUnt"`
	NFeSizeFontObs                        string    `gorm:"column:NFeSizeFontObs" json:"NFeSizeFontObs"`
	NFeValASS                             string    `gorm:"column:NFeVal_ASS" json:"NFeVal_ASS"`
	NFeValMD5                             string    `gorm:"column:NFeVal_MD5" json:"NFeVal_MD5"`
	PRPercentual                          float64   `gorm:"column:PRPercentual" json:"PRPercentual"`
	PRQtdeDiasLimite                      int64     `gorm:"column:PRQtdeDiasLimite" json:"PRQtdeDiasLimite"`
	PRQtdeVendaPremiar                    int64     `gorm:"column:PRQtdeVendaPremiar" json:"PRQtdeVendaPremiar"`
	UtilizaPremiacaoCorretor              bool      `gorm:"column:UtilizaPremiacaoCorretor;default:0" json:"UtilizaPremiacaoCorretor"`
	InformarPISCOFINSArquivoFortes        bool      `gorm:"column:InformarPISCOFINSArquivoFortes;not null;default:0" json:"InformarPISCOFINSArquivoFortes"`
	AddMensVendaNoOrcamento               bool      `gorm:"column:addMensVendaNoOrcamento" json:"addMensVendaNoOrcamento"`
	DescontoMaximoVarejo                  int64     `gorm:"column:DescontoMaximoVarejo" json:"DescontoMaximoVarejo"`
	ObrigaTelefoneCliente                 bool      `gorm:"column:ObrigaTelefoneCliente" json:"ObrigaTelefoneCliente"`
	NFeAutorizacao                        string    `gorm:"column:NFeAutorizacao" json:"NFeAutorizacao"`
	NFeRetAutorizacao                     string    `gorm:"column:NFeRetAutorizacao" json:"NFeRetAutorizacao"`
	ImprimeVendaBobina                    bool      `gorm:"column:ImprimeVendaBobina" json:"ImprimeVendaBobina"`
	LojaOnLine                            bool      `gorm:"column:LojaOnLine;not null;default:0" json:"LojaOnLine"`
	NFCeAmbiente                          int64     `gorm:"column:NFCeAmbiente" json:"NFCeAmbiente"`
	NFCeModelo                            int64     `gorm:"column:NFCeModelo" json:"NFCeModelo"`
	NFCePathPrincipal                     string    `gorm:"column:NFCePathPrincipal" json:"NFCePathPrincipal"`
	NFCeSerie                             int64     `gorm:"column:NFCeSerie" json:"NFCeSerie"`
	NFCeTipoDanfe                         int64     `gorm:"column:NFCeTipoDanfe" json:"NFCeTipoDanfe"`
	NFCeVersaoXML                         string    `gorm:"column:NFCeVersaoXML" json:"NFCeVersaoXML"`
	CalculaTributosAproximados            bool      `gorm:"column:CalculaTributosAproximados;default:1" json:"CalculaTributosAproximados"`
	DescontoSuframa                       float64   `gorm:"column:DescontoSuframa;not null" json:"DescontoSuframa"`
	DataFinalPeriodoBase                  time.Time `gorm:"column:DataFinalPeriodoBase" json:"DataFinalPeriodoBase"`
	SaldoICMS                             []uint8   `gorm:"column:SaldoICMS;not null;default:0" json:"SaldoICMS"`
	SaldoICMSTipo                         string    `gorm:"column:SaldoICMS_Tipo" json:"SaldoICMS_Tipo"`
	SaldoIPI                              []uint8   `gorm:"column:SaldoIPI;not null;default:0" json:"SaldoIPI"`
	SaldoIPITipo                          string    `gorm:"column:SaldoIPI_Tipo" json:"SaldoIPI_Tipo"`
	SaldoCOFINS                           []uint8   `gorm:"column:SaldoCOFINS;not null;default:0" json:"SaldoCOFINS"`
	SaldoCOFINSTipo                       string    `gorm:"column:SaldoCOFINS_Tipo" json:"SaldoCOFINS_Tipo"`
	SaldoPIS                              []uint8   `gorm:"column:SaldoPIS;not null;default:0" json:"SaldoPIS"`
	SaldoPISTipo                          string    `gorm:"column:SaldoPIS_Tipo" json:"SaldoPIS_Tipo"`
	Numero                                string    `gorm:"column:Numero" json:"Numero"`
	CodigoContabilista                    int64     `gorm:"column:CodigoContabilista;not null" json:"CodigoContabilista"`
	InformarItensdosDocumentosFiscais     bool      `gorm:"column:InformarItensdosDocumentosFiscais;not null;default:0" json:"InformarItensdosDocumentosFiscais"`
	CorPrimaria                           string    `gorm:"column:CorPrimaria" json:"CorPrimaria"`
	CorSecundaria                         string    `gorm:"column:CorSecundaria" json:"CorSecundaria"`
	TituloSite                            string    `gorm:"column:TituloSite" json:"TituloSite"`
	RodapeSite                            string    `gorm:"column:RodapeSite" json:"RodapeSite"`
	DescontoMaximoDinheiro                float64   `gorm:"column:DescontoMaximoDinheiro" json:"DescontoMaximoDinheiro"`
	DescontoMaximoCartao                  float64   `gorm:"column:DescontoMaximoCartao" json:"DescontoMaximoCartao"`
	ChavePIX                              string    `gorm:"column:ChavePIX" json:"ChavePIX"`
}

// TableName Loja's table name
func (*Loja) TableName() string {
	return TableNameLoja
}
