// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduto = "Produtos"

// Produto mapped from table <Produtos>
type Produto struct {
	Referencia                         string    `gorm:"column:Referencia;primaryKey" json:"Referencia"`
	Descricao                          string    `gorm:"column:Descricao" json:"Descricao"`
	UND                                string    `gorm:"column:UND" json:"UND"`
	Grade                              string    `gorm:"column:Grade" json:"Grade"`
	PrCompra                           []uint8   `gorm:"column:PrCompra;not null;default:0" json:"PrCompra"`
	PrCusto                            []uint8   `gorm:"column:PrCusto;not null;default:0" json:"PrCusto"`
	Preco1                             []uint8   `gorm:"column:Preco1;not null;default:0" json:"Preco1"`
	Preco2                             []uint8   `gorm:"column:Preco2;not null;default:0" json:"Preco2"`
	Preco3                             []uint8   `gorm:"column:Preco3;not null;default:0" json:"Preco3"`
	Preco4                             []uint8   `gorm:"column:Preco4;not null;default:0" json:"Preco4"`
	Preco5                             []uint8   `gorm:"column:Preco5;not null;default:0" json:"Preco5"`
	Preco6                             []uint8   `gorm:"column:Preco6;not null;default:0" json:"Preco6"`
	Colecao                            int64     `gorm:"column:Colecao;not null" json:"Colecao"`
	Linha                              int64     `gorm:"column:Linha;not null" json:"Linha"`
	Grupo                              int64     `gorm:"column:Grupo;not null" json:"Grupo"`
	CodigoBarras                       string    `gorm:"column:CodigoBarras" json:"CodigoBarras"`
	GradenaTabela                      string    `gorm:"column:GradenaTabela" json:"GradenaTabela"`
	Localizacao                        string    `gorm:"column:Localizacao" json:"Localizacao"`
	Pontuacao                          float64   `gorm:"column:Pontuacao;not null" json:"Pontuacao"`
	Composicao1                        string    `gorm:"column:Composicao1" json:"Composicao1"`
	Composicao2                        string    `gorm:"column:Composicao2" json:"Composicao2"`
	Composicao3                        string    `gorm:"column:Composicao3" json:"Composicao3"`
	Inativo                            bool      `gorm:"column:Inativo;not null;default:0" json:"Inativo"`
	DataBalanco                        time.Time `gorm:"column:DataBalanco" json:"DataBalanco"`
	Entradas                           int64     `gorm:"column:Entradas;not null" json:"Entradas"`
	Saidas                             int64     `gorm:"column:Saidas;not null" json:"Saidas"`
	Fornecedor                         int64     `gorm:"column:Fornecedor;not null" json:"Fornecedor"`
	CodigoOriginal                     string    `gorm:"column:CodigoOriginal" json:"CodigoOriginal"`
	UltimaCompraFornecedor             int64     `gorm:"column:UltimaCompraFornecedor;not null" json:"UltimaCompraFornecedor"`
	UltimaCompraData                   time.Time `gorm:"column:UltimaCompraData" json:"UltimaCompraData"`
	PrFuncionario                      []uint8   `gorm:"column:PrFuncionario;not null;default:0" json:"PrFuncionario"`
	KitReferencia1                     string    `gorm:"column:KitReferencia1" json:"KitReferencia1"`
	KitReferencia2                     string    `gorm:"column:KitReferencia2" json:"KitReferencia2"`
	KitReferencia3                     string    `gorm:"column:KitReferencia3" json:"KitReferencia3"`
	Tecido2                            string    `gorm:"column:Tecido2" json:"Tecido2"`
	Tecido1                            string    `gorm:"column:Tecido1" json:"Tecido1"`
	Composicao6                        string    `gorm:"column:Composicao6" json:"Composicao6"`
	Composicao5                        string    `gorm:"column:Composicao5" json:"Composicao5"`
	Composicao4                        string    `gorm:"column:Composicao4" json:"Composicao4"`
	ExcluirdaTabeladePreco             bool      `gorm:"column:ExcluirdaTabeladePreco;not null;default:0" json:"ExcluirdaTabeladePreco"`
	CoresdaTabela                      string    `gorm:"column:CoresdaTabela" json:"CoresdaTabela"`
	PrLD                               []uint8   `gorm:"column:PrLD;not null;default:0" json:"PrLD"`
	EntradasLD                         int64     `gorm:"column:EntradasLD;not null" json:"EntradasLD"`
	SaidasLD                           int64     `gorm:"column:SaidasLD;not null" json:"SaidasLD"`
	KitReferencia1TipoPeca             int64     `gorm:"column:KitReferencia1TipoPeca;not null" json:"KitReferencia1TipoPeca"`
	KitReferencia2TipoPeca             int64     `gorm:"column:KitReferencia2TipoPeca;not null" json:"KitReferencia2TipoPeca"`
	KitReferencia3TipoPeca             int64     `gorm:"column:KitReferencia3TipoPeca;not null" json:"KitReferencia3TipoPeca"`
	KitReferencia4                     string    `gorm:"column:KitReferencia4" json:"KitReferencia4"`
	KitReferencia4TipoPeca             int64     `gorm:"column:KitReferencia4TipoPeca;not null" json:"KitReferencia4TipoPeca"`
	Simbologia                         string    `gorm:"column:Simbologia" json:"Simbologia"`
	SubGrupo                           int64     `gorm:"column:SubGrupo;not null" json:"SubGrupo"`
	Genero                             int64     `gorm:"column:Genero;not null" json:"Genero"`
	Preco7                             []uint8   `gorm:"column:Preco7;not null;default:0" json:"Preco7"`
	DataBalancoLD                      time.Time `gorm:"column:DataBalancoLD" json:"DataBalancoLD"`
	MetaRepresentante                  int64     `gorm:"column:MetaRepresentante;not null" json:"MetaRepresentante"`
	CodigoNCM                          string    `gorm:"column:CodigoNCM" json:"CodigoNCM"`
	DataCadastro                       time.Time `gorm:"column:DataCadastro" json:"DataCadastro"`
	AjustedePrecoTipo                  string    `gorm:"column:AjustedePreco_Tipo" json:"AjustedePreco_Tipo"`
	AjustedePrecoData                  time.Time `gorm:"column:AjustedePreco_Data" json:"AjustedePreco_Data"`
	AjustedePrecoPercentual            float64   `gorm:"column:AjustedePreco_Percentual;not null" json:"AjustedePreco_Percentual"`
	AjustedePrecoUsuario               string    `gorm:"column:AjustedePreco_Usuario" json:"AjustedePreco_Usuario"`
	AjustedePrecoHora                  string    `gorm:"column:AjustedePreco_Hora" json:"AjustedePreco_Hora"`
	Preco8                             []uint8   `gorm:"column:Preco8;not null;default:0" json:"Preco8"`
	Preco9                             []uint8   `gorm:"column:Preco9;not null;default:0" json:"Preco9"`
	Preco10                            []uint8   `gorm:"column:Preco10;not null;default:0" json:"Preco10"`
	Origem                             int64     `gorm:"column:Origem;not null" json:"Origem"`
	Peso                               float64   `gorm:"column:Peso;not null" json:"Peso"`
	CodigoContabil                     int64     `gorm:"column:CodigoContabil;not null" json:"CodigoContabil"`
	Categoria                          int64     `gorm:"column:Categoria" json:"Categoria"`
	LocalizacaoPecaPiloto              string    `gorm:"column:LocalizacaoPecaPiloto" json:"LocalizacaoPecaPiloto"`
	PrMedio                            []uint8   `gorm:"column:PrMedio;not null;default:0" json:"PrMedio"`
	EntradaFinanceira                  []uint8   `gorm:"column:EntradaFinanceira;not null;default:0" json:"EntradaFinanceira"`
	SaidaFinanceira                    []uint8   `gorm:"column:SaidaFinanceira;not null;default:0" json:"SaidaFinanceira"`
	EstoqueMin                         int64     `gorm:"column:EstoqueMin" json:"EstoqueMin"`
	EstoqueMax                         int64     `gorm:"column:EstoqueMax" json:"EstoqueMax"`
	EstoqueMinimo                      int64     `gorm:"column:EstoqueMinimo;not null" json:"EstoqueMinimo"`
	SituacaoTributariaECF              string    `gorm:"column:SituacaoTributariaECF" json:"SituacaoTributariaECF"`
	IndicadorProducaoPropriaTerceiro   string    `gorm:"column:IndicadorProducaoPropriaTerceiro" json:"IndicadorProducaoPropriaTerceiro"`
	IndicadorArredondamentoTruncamento string    `gorm:"column:IndicadorArredondamentoTruncamento" json:"IndicadorArredondamentoTruncamento"`
	ReferenciaComercial                string    `gorm:"column:ReferenciaComercial" json:"ReferenciaComercial"`
	GrupoSped                          int64     `gorm:"column:GrupoSped" json:"GrupoSped"`
	DigitoVerificador                  int64     `gorm:"column:digitoVerificador" json:"digitoVerificador"`
	Tamanho                            string    `gorm:"column:tamanho" json:"tamanho"`
	Preco11                            []uint8   `gorm:"column:Preco11" json:"Preco11"`
	CodigoCEST                         string    `gorm:"column:CodigoCEST" json:"CodigoCEST"`
	IndicadorEscalaRelevante           string    `gorm:"column:IndicadorEscalaRelevante;default:S" json:"IndicadorEscalaRelevante"`
	CNPJFabricante                     string    `gorm:"column:CNPJFabricante" json:"CNPJFabricante"`
	CodigoBeneficioFiscalUF            string    `gorm:"column:CodigoBeneficioFiscalUF" json:"CodigoBeneficioFiscalUF"`
	ImagemFrente                       string    `gorm:"column:ImagemFrente" json:"ImagemFrente"`
	ImagemVerso                        string    `gorm:"column:ImagemVerso" json:"ImagemVerso"`
	AtivoEcommerce                     bool      `gorm:"column:AtivoEcommerce" json:"AtivoEcommerce"`
	DataAlteracao                      time.Time `gorm:"column:DataAlteracao" json:"DataAlteracao"`
	CSTPIS                             string    `gorm:"column:CST_PIS" json:"CST_PIS"`
	AliquotaPIS                        float64   `gorm:"column:Aliquota_PIS" json:"Aliquota_PIS"`
	CSTCOFINS                          string    `gorm:"column:CST_COFINS" json:"CST_COFINS"`
	AliquotaCOFINS                     float64   `gorm:"column:Aliquota_COFINS" json:"Aliquota_COFINS"`
	Detalhes                           string    `gorm:"column:Detalhes" json:"Detalhes"`
	CodigoICP                          string    `gorm:"column:CodigoICP" json:"CodigoICP"`
	AtivoCatalogo                      bool      `gorm:"column:AtivoCatalogo" json:"AtivoCatalogo"`
}

// TableName Produto's table name
func (*Produto) TableName() string {
	return TableNameProduto
}
