// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProdutosItem = "Produtos_Item"

// ProdutosItem mapped from table <Produtos_Item>
type ProdutosItem struct {
	Produto          string    `gorm:"column:Produto;primaryKey" json:"Produto"`
	Cor              int64     `gorm:"column:Cor;primaryKey" json:"Cor"`
	Ent01            int64     `gorm:"column:Ent01;not null" json:"Ent01"`
	Ent02            int64     `gorm:"column:Ent02;not null" json:"Ent02"`
	Ent03            int64     `gorm:"column:Ent03;not null" json:"Ent03"`
	Ent04            int64     `gorm:"column:Ent04;not null" json:"Ent04"`
	Ent05            int64     `gorm:"column:Ent05;not null" json:"Ent05"`
	Ent06            int64     `gorm:"column:Ent06;not null" json:"Ent06"`
	Ent07            int64     `gorm:"column:Ent07;not null" json:"Ent07"`
	Ent08            int64     `gorm:"column:Ent08;not null" json:"Ent08"`
	Ent09            int64     `gorm:"column:Ent09;not null" json:"Ent09"`
	Ent10            int64     `gorm:"column:Ent10;not null" json:"Ent10"`
	Sai01            int64     `gorm:"column:Sai01;not null" json:"Sai01"`
	Sai02            int64     `gorm:"column:Sai02;not null" json:"Sai02"`
	Sai03            int64     `gorm:"column:Sai03;not null" json:"Sai03"`
	Sai04            int64     `gorm:"column:Sai04;not null" json:"Sai04"`
	Sai05            int64     `gorm:"column:Sai05;not null" json:"Sai05"`
	Sai06            int64     `gorm:"column:Sai06;not null" json:"Sai06"`
	Sai07            int64     `gorm:"column:Sai07;not null" json:"Sai07"`
	Sai08            int64     `gorm:"column:Sai08;not null" json:"Sai08"`
	Sai09            int64     `gorm:"column:Sai09;not null" json:"Sai09"`
	Sai10            int64     `gorm:"column:Sai10;not null" json:"Sai10"`
	Preco1           []uint8   `gorm:"column:Preco1;not null;default:0" json:"Preco1"`
	Preco2           []uint8   `gorm:"column:Preco2;not null;default:0" json:"Preco2"`
	Preco3           []uint8   `gorm:"column:Preco3;not null;default:0" json:"Preco3"`
	Preco4           []uint8   `gorm:"column:Preco4;not null;default:0" json:"Preco4"`
	Preco5           []uint8   `gorm:"column:Preco5;not null;default:0" json:"Preco5"`
	Preco6           []uint8   `gorm:"column:Preco6;not null;default:0" json:"Preco6"`
	DataBalanco      time.Time `gorm:"column:DataBalanco" json:"DataBalanco"`
	KitCor1          int64     `gorm:"column:KitCor1;not null" json:"KitCor1"`
	KitCor2          int64     `gorm:"column:KitCor2;not null" json:"KitCor2"`
	KitCor3          int64     `gorm:"column:KitCor3;not null" json:"KitCor3"`
	KitCor4          int64     `gorm:"column:KitCor4;not null" json:"KitCor4"`
	Inativo          bool      `gorm:"column:Inativo;not null;default:0" json:"Inativo"`
	PorcentagemCorte float64   `gorm:"column:PorcentagemCorte" json:"PorcentagemCorte"`
	Imagem           string    `gorm:"column:Imagem" json:"Imagem"`
}

// TableName ProdutosItem's table name
func (*ProdutosItem) TableName() string {
	return TableNameProdutosItem
}
