// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSubGrupo = "SubGrupos"

// SubGrupo mapped from table <SubGrupos>
type SubGrupo struct {
	Codigo    int64  `gorm:"column:Codigo;primaryKey" json:"Codigo"`
	Descricao string `gorm:"column:Descricao" json:"Descricao"`
	Grupo     int64  `gorm:"column:Grupo;not null" json:"Grupo"`
}

// TableName SubGrupo's table name
func (*SubGrupo) TableName() string {
	return TableNameSubGrupo
}
